package constants

// Telegram only allows 64 bytes in callback_data,
// So we have to be really short :)
const (
	CmdShowStart          = "start"
	CmdDoNothing          = "nothing"
	CmdShowLater          = "later"
	CmdShowToday          = "today"
	CmdShowFiles          = "files"
	CmdShowPostpone       = "postpone"
	CmdShowRename         = "rename"
	CmdShowChecklists     = "checklists"
	CmdShowStats          = "stats"
	CmdComplete           = "c"
	CmdPostpone           = "post"
	CmdRenameFile         = "rename_file"
	CmdShowMultilineTask  = "task"
	CmdShowFile           = "file"
	CmdShowChecklist      = "checklist"
	CmdCompleteChecklist  = "cc"
	CmdShowChooseDay      = "to_day"
	CmdShowToFile         = "to_file"
	CmdShowToChecklist    = "to_checklist"
	CmdMoveToDir          = "mv"
	CmdMoveToNewDir       = "mv_to_new_dir"
	CmdMoveToExistingFile = "mvf"
	CmdMoveToNewFile      = "mv_to_new_doc"
	CmdMoveToChecklist    = "mv_to_chk"
	CmdMoveToNewChecklist = "mv_to_new_chk"
	CmdMoveJournal        = "mv_to_journal"
	CmdSchedule           = "sc"
	CmdPomodoro           = "pomodoro"
	CmdShowRecurringKB    = "recur_kb"
	CmdTomorrow           = "tomorrow"
	CmdLater              = "later"
	CmdShowSettings       = "settings"
	CmdConfigurePanel     = "configure_panel"
	CmdAddToPanel         = "panel_add"
	CmdDelFromPonel       = "panel_del"
	CmdShowReadChecklist  = "read"
	CmdShowWatchChecklist = "watch"
	CmdShowShopChecklist  = "shop"

	CmdInlineQuerySearchEveryWhere = "search"
	CmdInlineQuerySearchInDir      = "search_dir"
	CmdWebAppHabits                = "habits"
)
