zettel = {
    "arch": {
        "0 Agile architect.md":"# Some really smart words\n![Yes](https://i.imgur.com/sZlktY7.png)\nShould apply rational thinking at all times [[brain/Brain is the most complex object in known universe]]\n\n[[arch/0 Architecture]]",
        "0 Architecture.md": "\"Significant decisions are architecture, and everything else is design\"\n\nComputer architecture, like other architecture, is the art of determining the needs of the business of a structure and then designing to meet those needs as effectively as possible within economic and technological constraints\n\nПо поводу архитектуры - архитектура это всегда наличие ограничений, которые призваны дать какую-то характеристику.\n\n[[arch/0 Agile architect]]",
    },
    "brain": {
        "0 Learning.md": "### Learning is making meaningful connections\n\nЕсли нам дать время логически подумать - мы придем к одному. Но бОльшую роль имеют неявные небольшие решения, которые мы принимаем неосознанно в течении дня\n\n\"The one who does the work does the learning\"\n\n[[brain/Brain is the most complex object in known universe]]\n",
        "Brain is the most complex object in known universe.md": "Nothing will make you appreciate human intelligence like learning about how unbelievably challenging it is to try to create a computer as smart as we are. Building skyscrapers, putting humans in space, figuring out the details of how the Big Bang went down—all far easier than understanding our own brain or how to make something as cool as it\n\n\/\/ That's why road from ANI to AGI is so hard\n\/\/ AGI (a computer as smart as humans in general, not just at one narrow specialty\n\n[[brain/0 Learning]]",
        "Change your environment instead of using willpower.md": "When scientists analyze people who appear to have tremendous self-control, it turns out those individuals aren’t all that different from those who are struggling. Instead, “disciplined” people are better at structuring their lives in a way that does not require heroic willpower and self-control.\n\nIn other words, they spend less time in tempting situations. The people with the best self-control are typically the ones who need to use it the least.\n\n\/\/ Once a habit has been encoded, the urge to act follows whenever the environmental cues reappear\nWhen Patty Olwell, a therapist from Austin, Texas, started smoking, she would often light up while riding horses with a friend. Eventually, she quit smoking and avoided it for years. She had also stopped riding. Decades later, she hopped on a horse again and found herself craving a cigarette for the first time in forever. The cues were still internalized; she just hadn’t been exposed to them in a long time.",
    },
    "happiness": {
        "Abundant mediation.md": "Once you are relaxed, picture yourself living in an abundant world. In this abundant world, there are no restraints or limitations. Good things flow past you continuously. Imagine every abundant thing you have ever desired–car, home, friends, love, joy, wealth, success, peace of mind, challenge. Visualize yourself living your life surrounded by this abundance. Repeat this visualization several times a day until it begins to feel real to you. Open your arms, your heart, and your mind. Get out of the way, and let it happen.\n\n[[happiness/Boredom is just an emotion]]",
        "Boredom is just an emotion.md": "It's not an indicator that you're doing something wrong in your life\n\nBefore we had phones and technologies we would just sit around the fire and we would talk and we wouldn't call that boring that was just life\n\nAnd bow we have that endless need for entertainment, anything when nothing is happening we think it's wrong and we need to fix it\n\nNon eventfulness is just a part of our life and you can embrace it as\npeace or you can frantically try to create more chaos\n\n[[happiness/Abundant mediation]]",
    },
}
